.TH CONTACTS  1 "2007-1-15"
.SH NAME
contacts \- a light-weight address-book 
.SH DESCRIPTION
.B contacts
is a small, lightweight addressbook that features advanced vCard field
type handling and is designed for use on hand-held devices, such as the
.I Nokia 770
or the
.I Sharp Zaurus
series of
.I PDA\fRs.
.SS "Usage:"
.IP
.B contacts
.RB [ \ OPTION... ]
.SS "Help Options:"
.TP
\fB\-?\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-p\fR, \fB\-\-plug\fR
Socket ID of an XEmbed socket to plug into
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH "SEE ALSO"
http://projects.o-hand.com/contacts
.SH AUTHORS
.B
contacts
was written by by Chris Lord <chris@openedhand.com>.

.ad l
This manual page was written by Kestutis Biliunas
.nh 
<kebil@kaunas.init.lt>,
.hy
for the Debian system (but may be used by others).
